version: '3'

services:
  kash_mysql:
    image: mysql:latest
    container_name: kash_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: kash_laravel_db
      MYSQL_USER: kash_laravel_user
      MYSQL_PASSWORD: kash_laravel_db_laravel_password
    volumes:
      - kash_mysql_volume:/var/lib/mysql
    networks:
      - kash_network

  kash_php:
    build:
      dockerfile: devops/docker/php.dockerfile
    container_name: kash_php
    volumes:
      - ./:/var/www/html
    depends_on:
      - kash_mysql
    networks:
      - kash_network
      
  kash_nginx:
    image: nginx:latest
    container_name: kash_nginx
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./devops/docker/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - kash_php
    networks:
      - kash_network

networks:
  kash_network:
    driver: bridge

volumes:
  kash_mysql_volume: